### ISSUE TITLE
在运行bash ./scripts/train_wikievent_roberta.sh时出现了KeyError: 'id'错误

### ISSUE THREAD

**Issue by daisir8** [LWL-cpu/DEEIA#2]
'roberta.encoder.layer.22.crossattention.self.abs_bias.1', 'roberta.encoder.layer.8.attention.self.abs_bias.0', 'roberta.encoder.layer.9.attention.self.abs_bias.1', 'roberta.encoder.layer.5.attention.self.abs_bias.0', 'roberta.encoder.layer.17.crossattention.self.key.weight', 'roberta.encoder.layer.22.crossattention.self.query.weight', 'roberta.encoder.layer.22.crossattention.self.query.bias', 'roberta.encoder.layer.21.crossattention.self.query.bias', 'roberta.encoder.layer.22.crossattention.self.value.weight', 'roberta.encoder.layer.2.attention.self.abs_bias.1', 'roberta.encoder.layer.17.crossattention.output.dense.bias', 'roberta.encoder.layer.21.crossattention.self.query.weight', 'roberta.encoder.layer.20.crossattention.output.LayerNorm.bias', 'roberta.encoder.layer.18.attention.self.abs_bias.0', 'roberta.encoder.layer.19.attention.self.abs_bias.1', 'roberta.encoder.layer.1.attention.self.bili.0', 'roberta.encoder.layer.8.attention.self.bili.0', 'roberta.encoder.layer.17.crossattention.output.LayerNorm.weight', 'roberta.encoder.layer.19.crossattention.self.key.weight', 'roberta.encoder.layer.14.attention.self.abs_bias.0', 'roberta.encoder.layer.23.crossattention.self.abs_bias.0', 'roberta.encoder.layer.12.attention.self.abs_bias.0', 'roberta.encoder.layer.10.attention.self.bili.0', 'roberta.encoder.layer.23.crossattention.output.dense.weight', 'roberta.encoder.layer.21.crossattention.self.abs_bias.1', 'roberta.encoder.layer.18.crossattention.self.query.weight', 'roberta.encoder.layer.23.crossattention.self.query.bias', 'roberta.encoder.layer.20.crossattention.self.abs_bias.1', 'roberta.encoder.layer.22.crossattention.self.value.bias', 'roberta.encoder.layer.18.crossattention.output.dense.bias', 'roberta.encoder.layer.2.attention.self.bili.1', 'roberta.encoder.layer.12.attention.self.bili.1', 'roberta.encoder.layer.23.crossattention.self.value.bias', 'roberta.encoder.layer.4.attention.self.abs_bias.0', 'roberta.encoder.layer.22.crossattention.self.key.weight', 'roberta.encoder.layer.20.crossattention.output.dense.weight', 'roberta.encoder.layer.20.crossattention.self.key.bias', 'roberta.encoder.layer.17.crossattention.self.value.bias', 'roberta.encoder.layer.6.attention.self.bili.1', 'roberta.encoder.layer.15.attention.self.abs_bias.0', 'roberta.encoder.layer.22.attention.self.abs_bias.1', 'roberta.encoder.layer.18.crossattention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.self.bili.1', 'roberta.encoder.layer.14.attention.self.abs_bias.1', 'roberta.encoder.layer.19.crossattention.output.dense.bias', 'roberta.encoder.layer.20.crossattention.self.query.weight', 'roberta.encoder.layer.22.crossattention.self.abs_bias.0', 'roberta.encoder.layer.1.attention.self.bili.1', 'w_prompt_end', 'roberta.encoder.layer.20.crossattention.self.value.bias', 'roberta.encoder.layer.21.crossattention.output.dense.weight', 'roberta.encoder.layer.5.attention.self.abs_bias.1', 'roberta.encoder.layer.19.crossattention.output.dense.weight', 'roberta.encoder.layer.23.crossattention.self.query.weight', 'roberta.encoder.layer.15.attention.self.abs_bias.1', 'roberta.encoder.layer.6.attention.self.abs_bias.0', 'roberta.encoder.layer.18.crossattention.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.self.bili.0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/ubuntu/下载/DEEIA-master/engine.py", line 73, in <module>
    main()
  File "/home/ubuntu/下载/DEEIA-master/engine.py", line 67, in main
    run(args, model, processor, optimizer, scheduler)
  File "/home/ubuntu/下载/DEEIA-master/engine.py", line 17, in run
    train_examples, train_features, train_dataloader, args.train_invalid_num = processor.generate_dataloader('train')
  File "/home/ubuntu/下载/DEEIA-master/processors/processor_base.py", line 320, in generate_dataloader
    examples = self.create_example(file_path, set_type)
  File "/home/ubuntu/下载/DEEIA-master/processors/processor_base.py", line 213, in create_example
    return self._create_example(lines, over_sample=('double' if set_type == 'train' else None))
  File "/home/ubuntu/下载/DEEIA-master/processors/processor_base.py", line 128, in _create_example
    doc_id = line["id"]
KeyError: 'id'

具体出现的问题如上，谢谢作者

**Comment by LWL-cpu** [comment]
很抱歉，忘记提及数据处理的细节。由于这是多事件EAE任务，我们在处理数据时参考了TabEAE的预处理流程，对原始文档进行了相应处理。您可以查看TabEAE的 download_data.sh 脚本以获取具体的处理步骤和细节。希望这对您有所帮助！
