### ISSUE TITLE
DEEIA.py中的“decoder_prompt_output”语句只出现过一次，我没有在其他地方找到声明和定义

### ISSUE THREAD

**Issue by daisir8** [LWL-cpu/DEEIA#3]
Traceback (most recent call last):
  File "/home/ubuntu/下载/DEEIA-master/engine.py", line 73, in <module>
    main()
  File "/home/ubuntu/下载/DEEIA-master/engine.py", line 67, in main
    run(args, model, processor, optimizer, scheduler)
  File "/home/ubuntu/下载/DEEIA-master/engine.py", line 33, in run
    runner.run()
  File "/home/ubuntu/下载/DEEIA-master/runner/runner.py", line 151, in run
    self.train()
  File "/home/ubuntu/下载/DEEIA-master/runner/runner.py", line 76, in train
    self.trainer.train_one_step()
  File "/home/ubuntu/下载/DEEIA-master/runner/train.py", line 60, in train_one_step
    loss, _ = self.model(**inputs)
  File "/home/ubuntu/anaconda3/envs/DEEIA/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/下载/DEEIA-master/models/DEEIA.py", line 107, in forward
    prompt_query_sub = decoder_prompt_output[p_start:p_end]
NameError: name 'decoder_prompt_output' is not defined

DEEIA.py中的“decoder_prompt_output”语句只出现过一次，我没有在其他地方找到声明和定义，同时该问题也出现了报错，报错信息如上

**Comment by LWL-cpu** [comment]
很抱歉，这段代码是之前版本的，确实存在一些 bug。现在我们已经修复了这个问题，将 decoder_prompt_output 替换为正确的变量名。请您更新到最新版本并再次尝试，如有其他问题请随时反馈！
