### ISSUE TITLE
在使用 PyTorch 的 torch.tanh 函数时遇到了维度不匹配的问题

### ISSUE THREAD

**Issue by daisir8** [LWL-cpu/DEEIA#4]
Traceback (most recent call last):
  File "/home/ubuntu/下载/DEEIA-master/engine.py", line 73, in <module>
    main()
  File "/home/ubuntu/下载/DEEIA-master/engine.py", line 67, in main
    run(args, model, processor, optimizer, scheduler)
  File "/home/ubuntu/下载/DEEIA-master/engine.py", line 33, in run
    runner.run()
  File "/home/ubuntu/下载/DEEIA-master/runner/runner.py", line 151, in run
    self.train()
  File "/home/ubuntu/下载/DEEIA-master/runner/runner.py", line 76, in train
    self.trainer.train_one_step()
  File "/home/ubuntu/下载/DEEIA-master/runner/train.py", line 60, in train_one_step
    loss, _ = self.model(**inputs)
  File "/home/ubuntu/anaconda3/envs/DEEIA/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/下载/DEEIA-master/models/DEEIA.py", line 122, in forward
    prompt_query_sub = torch.tanh(self.contextual_merger(torch.cat((prompt_query_sub, context_rs), dim=-1)))
RuntimeError: Tensors must have same number of dimensions: got 3 and 2
作者你好！打扰您了，我现在在使用 PyTorch 的 torch.tanh 函数时遇到了维度不匹配的问题。torch.tanh 函数要求输入的张量（tensor）必须是相同维度的，但在你的代码中，torch.cat 函数合并后的张量和 torch.tanh 函数期望的输入张量维度不一致。我不知道如何调整这维度，我害怕我的盲目调整会影响到代码的运行结果，所以向您寻求帮助。

**Comment by JJC-CH** [comment]
我也遇到了类似的问题Traceback (most recent call last):
  File "/hy-tmp/engine.py", line 73, in <module>
    main()
  File "/hy-tmp/engine.py", line 67, in main
    run(args, model, processor, optimizer, scheduler)
  File "/hy-tmp/engine.py", line 33, in run
    runner.run()
  File "/hy-tmp/runner/runner.py", line 151, in run
    self.train()
  File "/hy-tmp/runner/runner.py", line 76, in train
    self.trainer.train_one_step()
  File "/hy-tmp/runner/train.py", line 45, in train_one_step
    batch = next(self.data_iterator)
  File "/usr/local/miniconda3/envs/DEEIA/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/local/miniconda3/envs/DEEIA/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/miniconda3/envs/DEEIA/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/hy-tmp/processors/processor_multiarg.py", line 168, in collate_fn
    dec_prompt_ids = torch.tensor([f.dec_prompt_ids for f in batch])
ValueError: expected sequence of length 64 at dim 1 (got 76)
作者您好，打扰您一下，在collate_fn 函数中，某些样本的 dec_prompt_ids 的长度不一致，模型期望长度为 64，但实际长度为 76。，这应该怎么处理，所以向您寻求帮助
