### ISSUE TITLE
数据的维度问题和代码的结果问题

### ISSUE THREAD

**Issue by JJC-CH** [LWL-cpu/DEEIA#6]
作者您好，非常抱歉打扰您了，我在RAMS_1.0数据集和MLEE数据集上运行代码的时候，分别出现了如下问题：
Traceback (most recent call last):
  File "/hy-tmp/engine.py", line 73, in <module>
    main()
  File "/hy-tmp/engine.py", line 67, in main
    run(args, model, processor, optimizer, scheduler)
  File "/hy-tmp/engine.py", line 33, in run
    runner.run()
  File "/hy-tmp/runner/runner.py", line 151, in run
    self.train()
  File "/hy-tmp/runner/runner.py", line 76, in train
    self.trainer.train_one_step()
  File "/hy-tmp/runner/train.py", line 45, in train_one_step
    batch = next(self.data_iterator)
  File "/usr/local/miniconda3/envs/DEEIA/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/local/miniconda3/envs/DEEIA/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/miniconda3/envs/DEEIA/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/hy-tmp/processors/processor_multiarg.py", line 168, in collate_fn
    dec_prompt_ids = torch.tensor([f.dec_prompt_ids for f in batch])
ValueError: expected sequence of length 67 at dim 1 (got 64)

----------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/hy-tmp/engine.py", line 73, in <module>
    main()
  File "/hy-tmp/engine.py", line 67, in main
    run(args, model, processor, optimizer, scheduler)
  File "/hy-tmp/engine.py", line 33, in run
    runner.run()
  File "/hy-tmp/runner/runner.py", line 151, in run
    self.train()
  File "/hy-tmp/runner/runner.py", line 76, in train
    self.trainer.train_one_step()
  File "/hy-tmp/runner/train.py", line 45, in train_one_step
    batch = next(self.data_iterator)
  File "/usr/local/miniconda3/envs/DEEIA/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/local/miniconda3/envs/DEEIA/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/miniconda3/envs/DEEIA/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/hy-tmp/processors/processor_multiarg.py", line 168, in collate_fn
    dec_prompt_ids = torch.tensor([f.dec_prompt_ids for f in batch])
ValueError: expected sequence of length 64 at dim 1 (got 76)
./scripts/train_rams_roberta.sh: line 23: --
两个都出现了维度不匹配问题，我想知道这块代码您是如何做的，我应该如何解决这个问题。

在WikiEvent数据集上面，运行后出现best_dev_results.log文件和best_test_related_results.log，这两个里面都只记录了一个dev best score: P: 0.5662650602409639 R: 0.5490654205607477 f1: 0.5575326215895612和test related best score: P: 0.6829787234042554 R: 0.5671378091872792 f1: 0.6196911196911197这种的 P R F1，没有找到您论文当中提到的Arg-I和Arg-C两个指标的F1分数，在log.txt当中 span-Classification、 span-Identification、 text-Classification、 text-Identification、head-Classification、head-Identification.在您论文当中也没有提到，我想知道这些具体作用是什么，也没有找到两个Arg-I和Arg-C两个指标当中的F1分数，您输出的best_dev_results.log文件和best_test_related_results.log文件是不是记录的是在验证集和测试集上面最好的结果，但是我不知道这个里面 的 P R F1分数是计算的哪个评估指标（Arg-I和Arg-C）
期待您的回复！

**Comment by simon-p-j-r** [comment]
请问您有修复这个问题吗？我也遇到了相似的情况

**Comment by simon-p-j-r** [comment]
查看了一下，需要设置一下config_parser.py中max_prompt_seq_length这个参数的值。

**Comment by Zhenyu-Song** [comment]
RAMS_1.0没遇到报错，MLEE数据集需要在train_mlee_roberta.sh中加上--max_prompt_seq_length参数

**Comment by donggedashao** [comment]
> RAMS_1.0没遇到报错，MLEE数据集需要在train_mlee_roberta.sh中加上--max_prompt_seq_length参数

请问设置成--max_prompt_seq_length 360 \这样对吗？还有--max_dec_seq_length 512 \要删掉吗？

**Comment by simon-p-j-r** [comment]
> > RAMS_1.0没遇到报错，MLEE数据集需要在train_mlee_roberta.sh中加上--max_prompt_seq_length参数
> 
> 请问设置成--max_prompt_seq_length 360 \这样对吗？还有--max_dec_seq_length 512 \要删掉吗？

可以试试360行不行；不删。

**Comment by donggedashao** [comment]
> 可以试试360行不行；不删。
好多谢谢。还有请问下论文里的结果Arg-I和Arg-C是看哪两个值呢？
05/09/2025 11:39:24 - INFO - runner.evaluate -   span-Classification. DEV (2188): R 0.46983546617915906 P 0.5084075173095944 F 0.4883610451306413
05/09/2025 11:39:24 - INFO - runner.evaluate -   span-Identification. DEV (2045): R 0.5100244498777506 P 0.5565635005336179 F 0.5322786425108447
05/09/2025 11:39:24 - INFO - runner.evaluate -   text-Classification. DEV (2188): R 0.5109689213893968 P 0.552917903066271 F 0.5311163895486936
05/09/2025 11:39:24 - INFO - runner.evaluate -   text-Identification. DEV (2041): R 0.5531602155805977 P 0.6053619302949061 F 0.5780849974398362
05/09/2025 11:39:34 - INFO - runner.evaluate -   head-Classification. DEV (2188): R 0.5749542961608776 P 0.6224641266699653 F 0.5977666904252792
05/09/2025 11:39:34 - INFO - runner.evaluate -   head-Identification. DEV (2036): R 0.6247544204322201 P 0.6879394267171444 F 0.6548262548262549
05/09/2025 11:40:14 - INFO - runner.evaluate -   span-Classification. TEST (2023): R 0.5037073652990608 P 0.535751840168244 F 0.5192356687898089
05/09/2025 11:40:14 - INFO - runner.evaluate -   span-Identification. TEST (1897): R 0.5429625724828677 P 0.5819209039548022 F 0.5617671120807199
05/09/2025 11:40:14 - INFO - runner.evaluate -   text-Classification. TEST (2023): R 0.5442412259021255 P 0.5788643533123028 F 0.5610191082802548
05/09/2025 11:40:14 - INFO - runner.evaluate -   text-Identification. TEST (1894): R 0.5897571277719112 P 0.6332199546485261 F 0.6107162383816294
05/09/2025 11:40:23 - INFO - runner.evaluate -   head-Classification. TEST (2023): R 0.6119624320316361 P 0.650893796004206 F 0.6308280254777069
05/09/2025 11:40:23 - INFO - runner.evaluate -   head-Identification. TEST (1890): R 0.6619047619047619 P 0.714041095890411 F 0.6869851729818781
05/09/2025 11:40:23 - INFO - runner.runner -   current best dev-f1 score: 0.4969638085984941
05/09/2025 11:40:23 - INFO - runner.runner -   current related test-f1 score: 0.5170528508200989

**Comment by donggedashao** [comment]
> > > RAMS_1.0没遇到报错，MLEE数据集需要在train_mlee_roberta.sh中加上--max_prompt_seq_length参数
> > 
> > 
> > 请问设置成--max_prompt_seq_length 360 \这样对吗？还有--max_dec_seq_length 512 \要删掉吗？
> 
> 可以试试360行不行；不删。

好的谢谢。还有请问下论文里的结果Arg-I和Arg-C是看哪两个值呢？
05/09/2025 11:39:24 - INFO - runner.evaluate - span-Classification. DEV (2188): R 0.46983546617915906 P 0.5084075173095944 F 0.4883610451306413
05/09/2025 11:39:24 - INFO - runner.evaluate - span-Identification. DEV (2045): R 0.5100244498777506 P 0.5565635005336179 F 0.5322786425108447
05/09/2025 11:39:24 - INFO - runner.evaluate - text-Classification. DEV (2188): R 0.5109689213893968 P 0.552917903066271 F 0.5311163895486936
05/09/2025 11:39:24 - INFO - runner.evaluate - text-Identification. DEV (2041): R 0.5531602155805977 P 0.6053619302949061 F 0.5780849974398362
05/09/2025 11:39:34 - INFO - runner.evaluate - head-Classification. DEV (2188): R 0.5749542961608776 P 0.6224641266699653 F 0.5977666904252792
05/09/2025 11:39:34 - INFO - runner.evaluate - head-Identification. DEV (2036): R 0.6247544204322201 P 0.6879394267171444 F 0.6548262548262549
05/09/2025 11:40:14 - INFO - runner.evaluate - span-Classification. TEST (2023): R 0.5037073652990608 P 0.535751840168244 F 0.5192356687898089
05/09/2025 11:40:14 - INFO - runner.evaluate - span-Identification. TEST (1897): R 0.5429625724828677 P 0.5819209039548022 F 0.5617671120807199
05/09/2025 11:40:14 - INFO - runner.evaluate - text-Classification. TEST (2023): R 0.5442412259021255 P 0.5788643533123028 F 0.5610191082802548
05/09/2025 11:40:14 - INFO - runner.evaluate - text-Identification. TEST (1894): R 0.5897571277719112 P 0.6332199546485261 F 0.6107162383816294
05/09/2025 11:40:23 - INFO - runner.evaluate - head-Classification. TEST (2023): R 0.6119624320316361 P 0.650893796004206 F 0.6308280254777069
05/09/2025 11:40:23 - INFO - runner.evaluate - head-Identification. TEST (1890): R 0.6619047619047619 P 0.714041095890411 F 0.6869851729818781
05/09/2025 11:40:23 - INFO - runner.runner - current best dev-f1 score: 0.4969638085984941
05/09/2025 11:40:23 - INFO - runner.runner - current related test-f1 score: 0.5170528508200989

**Comment by simon-p-j-r** [comment]
span test



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LWL-cpu/DEEIA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年5月9日(星期五) 中午1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LWL-cpu/DEEIA] 数据的维度问题和代码的结果问题 (Issue #6)



 donggedashao left a comment (LWL-cpu/DEEIA#6)
    
RAMS_1.0没遇到报错，MLEE数据集需要在train_mlee_roberta.sh中加上--max_prompt_seq_length参数
  
请问设置成--max_prompt_seq_length 360 \这样对吗？还有--max_dec_seq_length 512 \要删掉吗？
  
可以试试360行不行；不删。
  
好多谢谢。还有请问下论文里的结果Arg-I和Arg-C是看哪两个值呢？
 05/09/2025 11:39:24 - INFO - runner.evaluate - span-Classification. DEV (2188): R 0.46983546617915906 P 0.5084075173095944 F 0.4883610451306413
 05/09/2025 11:39:24 - INFO - runner.evaluate - span-Identification. DEV (2045): R 0.5100244498777506 P 0.5565635005336179 F 0.5322786425108447
 05/09/2025 11:39:24 - INFO - runner.evaluate - text-Classification. DEV (2188): R 0.5109689213893968 P 0.552917903066271 F 0.5311163895486936
 05/09/2025 11:39:24 - INFO - runner.evaluate - text-Identification. DEV (2041): R 0.5531602155805977 P 0.6053619302949061 F 0.5780849974398362
 05/09/2025 11:39:34 - INFO - runner.evaluate - head-Classification. DEV (2188): R 0.5749542961608776 P 0.6224641266699653 F 0.5977666904252792
 05/09/2025 11:39:34 - INFO - runner.evaluate - head-Identification. DEV (2036): R 0.6247544204322201 P 0.6879394267171444 F 0.6548262548262549
 05/09/2025 11:40:14 - INFO - runner.evaluate - span-Classification. TEST (2023): R 0.5037073652990608 P 0.535751840168244 F 0.5192356687898089
 05/09/2025 11:40:14 - INFO - runner.evaluate - span-Identification. TEST (1897): R 0.5429625724828677 P 0.5819209039548022 F 0.5617671120807199
 05/09/2025 11:40:14 - INFO - runner.evaluate - text-Classification. TEST (2023): R 0.5442412259021255 P 0.5788643533123028 F 0.5610191082802548
 05/09/2025 11:40:14 - INFO - runner.evaluate - text-Identification. TEST (1894): R 0.5897571277719112 P 0.6332199546485261 F 0.6107162383816294
 05/09/2025 11:40:23 - INFO - runner.evaluate - head-Classification. TEST (2023): R 0.6119624320316361 P 0.650893796004206 F 0.6308280254777069
 05/09/2025 11:40:23 - INFO - runner.evaluate - head-Identification. TEST (1890): R 0.6619047619047619 P 0.714041095890411 F 0.6869851729818781
 05/09/2025 11:40:23 - INFO - runner.runner - current best dev-f1 score: 0.4969638085984941
 05/09/2025 11:40:23 - INFO - runner.runner - current related test-f1 score: 0.5170528508200989
